#Dubbo 服务提供者配置
spring:
  dubbo:
    application:
      name: provider    #服务名称
    registry:
      address: zookeeper://192.168.157.128:2181   #注册中心地址
#    registry:
#      address: zookeeper://192.168.189.50:2181   #注册中心地址我的
    protocol:
      name: dubbo     #dubbo 协议
      port: 20880
    scan: com.lengedyun.dubbo_producer.service     #声明需要暴露的服务接口
